### PR TITLE
Create version of bioformats2raw that can be used for converting IDR studies

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/IDR/deployment/issues/389 for the context

This PR contains the minimal changes to evaluate the conversion of historical IDR studies which rely on a proprietary fork of OME Bio-Formats.

### CODE REVIEW

**Comment by dominikl** [comment]
Could we merge and release an "IDR bioformats2raw"? And maybe even push to conda? Would make it much easier setting up an NGFF conversion environment. Now we have to always say "Go to this PR, get the zip from the artifacts (which even disappears again a certain number of days)... etc."

**Comment by will-moore** [comment]
I can't actually see where to download the artifacts? 
Under the Successful runs above I see `The logs for this run have expired and are no longer available.`
Is there where the artifacts would be?
Which build would I want? 8, 11 or 17?

**Comment by dominikl** [comment]
I think @sbesson has to close and re-open the PR so that they get built again.

**Comment by sbesson** [comment]
I can certainly push another commit for the latest IDR Bio-Formats fixes which should be released in `prod116` which should trigger another artifact build via GitHub Actions.

If we need some form of persistency, we can certainly merge this in and create a tag (either `0.x.0` or including a suffix to avoid confusion with the upstream `bioformats2raw` releases) to generate a bundle of the converter as a GitHub release asset.

**Comment by will-moore** [comment]
@sbesson sounds great, thanks!

**Pull request merged**
